### ISSUE TITLE
новые виды

### ISSUE THREAD

**Issue by kuzmichevdima** [DariaFil/Python3#1]
https://github.com/DariaFil/Python3/blob/1414a92bc5adaec72bc7475e50469dfb277d8caa/lib.py#L33-L53

https://github.com/DariaFil/Python3/blob/1414a92bc5adaec72bc7475e50469dfb277d8caa/lib.py#L56-L66

что, если нам понадобится добавить еще 10 видов? здесь появится еще 10 функций? Код должен быть по условию гибкий, поэтому можно виды реализовать в виде классов, например

**Comment by DariaFil** [comment]
В последнем коммите добавила вместо функций поведения классы с общим интерфейсом. Теперь добавить новый вид можно, просто создав новый класс и переопределив в нём функции поведения и кодирования.
