### ISSUE TITLE
документация

### ISSUE THREAD

**Issue by kuzmichevdima** [DariaFil/Python3#11]
сейчас есть описания методов, но ничего нет про аргументы.

**Comment by DariaFil** [comment]
Добавлены комментарии к переменным

**Comment by kuzmichevdima** [comment]
См. примеры документации методов. Должны быть описания аргументов и того, что возвращает функция (if any)

**Comment by DariaFil** [comment]
Документация расширена и написана в соответствии с code style

**Comment by kuzmichevdima** [comment]
https://github.com/DariaFil/Python3/blob/c932fc5e57157bd83ea4c07429f1f84499df26fc/lib.py#L2-L6

https://github.com/DariaFil/Python3/blob/c932fc5e57157bd83ea4c07429f1f84499df26fc/lib.py#L28-L30

везде что-то с выравниванием этих комментов

**Comment by DariaFil** [comment]
Комменты выровняю единообразно сейчас же
