### ISSUE TITLE
неудобство

### ISSUE THREAD

**Issue by kuzmichevdima** [DariaFil/Python3#13]
https://github.com/DariaFil/Python3/blob/65603cb08a26cad76e0c54dfe28eac536fb71edf/lib.py#L80-L85

то есть, если я захочу новый вид добавить, мне нужно еще что-то в коде менять?
Нужно сделать, чтобы перебор всех видов происходил автоматически (например, используя спец метод _ _ subclasses_ _ от общего предка)

**Comment by DariaFil** [comment]
С использованием метода __subclasses__ проблема необходимости обновления словарей решена (сами словари убраны). Игра не содержит конкретных типов игровых объектов и оперирует только их общим предком PlayingObject
