### ISSUE TITLE
сокращения

### ISSUE THREAD

**Issue by kuzmichevdima** [DariaFil/Python3#14]
https://github.com/DariaFil/Python3/blob/65603cb08a26cad76e0c54dfe28eac536fb71edf/lib.py#L97-L100

почему бы не написать в одну строчку return ...

**Comment by kuzmichevdima** [comment]
https://github.com/DariaFil/Python3/blob/65603cb08a26cad76e0c54dfe28eac536fb71edf/lib.py#L68-L69

почему не в 1 строчку? В других классах аналогично

**Comment by DariaFil** [comment]
Сокращения выполнены
