### ISSUE TITLE
скорость

### ISSUE THREAD

**Issue by kuzmichevdima** [DariaFil/Python3#15]
https://github.com/DariaFil/Python3/blob/65603cb08a26cad76e0c54dfe28eac536fb71edf/lib.py#L38
вызов 2 раза перебора соседей - медленно. А если у меня будет вид, которому нужно 10 других видов вокруг посчитать?
Можно просто в том методе считать количество соседей каждого вида, а не только какого-то одного.

**Comment by DariaFil** [comment]
Метод update_cell переписан
