### ISSUE TITLE
ввод из stdin/файла, вывод в stdout/файл

### ISSUE THREAD

**Issue by kuzmichevdima** [DariaFil/Python3#2]
https://github.com/DariaFil/Python3/blob/1414a92bc5adaec72bc7475e50469dfb277d8caa/lib.py#L74-L81

https://github.com/DariaFil/Python3/blob/1414a92bc5adaec72bc7475e50469dfb277d8caa/lib.py#L91-L106

ввод должен быть одинаков из файла или stdin. Просто если ввод из файла, то нужно перенаправить stdin, что делается в 1 строку. Для вывода аналогично.

**Comment by DariaFil** [comment]
Ввод и вывод переделаны. В зависимости от "флага" либо перенаправляется stdin и stdout, либо открываются файлы. В последнем коммите присутствует заготовка для исправления последнего issue, пока что она не имеет значения.
