### ISSUE TITLE
названия

### ISSUE THREAD

**Issue by kuzmichevdima** [DariaFil/Python3#6]
https://github.com/DariaFil/Python3/blob/1055a5ed5cd8191950eeb464b3850538a67dca0d/lib.py#L130-L131

https://github.com/DariaFil/Python3/blob/1055a5ed5cd8191950eeb464b3850538a67dca0d/lib.py#L137-L139

diction, undiction, f, l, arr2 и так далее ничего не говорят, нужно менять.

i и j в маленьких кусочках кода допустимы, но это стандартные названия переменных цикла

**Comment by DariaFil** [comment]
Переменные переименованы

**Comment by kuzmichevdima** [comment]
https://github.com/DariaFil/Python3/blob/edd9ef4ccb9dc1ca5f35a2c8128366b5a81c31ab/lib.py#L119
https://github.com/DariaFil/Python3/blob/edd9ef4ccb9dc1ca5f35a2c8128366b5a81c31ab/lib.py#L125
 при использовании в названии arr понятнее не становится, что за переменная

https://github.com/DariaFil/Python3/blob/edd9ef4ccb9dc1ca5f35a2c8128366b5a81c31ab/lib.py#L109
c

https://github.com/DariaFil/Python3/blob/edd9ef4ccb9dc1ca5f35a2c8128366b5a81c31ab/lib.py#L2
по названию класса (Объект) абсолютно непонятно, что это

**Comment by DariaFil** [comment]
Переменные переименованы
